spring:
  datasource:
    url: jdbc:oracle:thin:@db202202221517_high?TNS_ADMIN=../Wallet
    username: ADMIN
    password: ParkJinKyum1025
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: true
      format_sql: true